CREATE TABLE USUARIO (
    USUARIO_ID CHAR(10) PRIMARY KEY,
    NOMBRE_USUARIO VARCHAR2(100) NOT NULL,
    APELLIDO_USUARIO VARCHAR2(100) NOT NULL,
    EMAIL_USUARIO VARCHAR2(100) NOT NULL UNIQUE,
    ROL_USUARIO VARCHAR2(50) NOT NULL,
    TELEFONO VARCHAR2(15) NOT NULL
);


CREATE TABLE ACTIVO (
    ACTIVO_ID CHAR(10) PRIMARY KEY,
    NOMBRE_ACTIVO VARCHAR2(100) NOT NULL,
    TIPO_ACTIVO VARCHAR2(50) NOT NULL CHECK (TIPO_ACTIVO IN ('Servidor', 'Router', 'Switch', 'PC', 'Dispositivo móvil', 'Otro')),
    DIRECCION_IP VARCHAR2(15) NOT NULL,
    DIRECCION_MAC VARCHAR2(17) NOT NULL
);


CREATE TABLE INCIDENTE (
    INCIDENTE_ID CHAR(10) PRIMARY KEY,
    ACTIVO_ID CHAR(10) NOT NULL,
    USUARIO_ID CHAR(10) NOT NULL,
    DESCRIPCION VARCHAR2(500) NOT NULL,
    FECHA DATE NOT NULL,
    GRAVEDAD VARCHAR2(20) NOT NULL CHECK (GRAVEDAD IN ('Baja', 'Media', 'Alta', 'Crítica')),
    ESTADO VARCHAR2(20) NOT NULL CHECK (ESTADO IN ('Abierto', 'En Proceso', 'Cerrado', 'Escalado')),
    CONSTRAINT FK_INCIDENTE_ACTIVO FOREIGN KEY (ACTIVO_ID) REFERENCES ACTIVO(ACTIVO_ID) ON DELETE CASCADE,
    CONSTRAINT FK_INCIDENTE_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(USUARIO_ID) ON DELETE CASCADE
);

-- IR (INCIDENT RESPONSE)
CREATE TABLE EQUIPO_IR (
    EQUIPO_ID CHAR(10) PRIMARY KEY,
    NOMBRE_EQUIPO VARCHAR2(100) NOT NULL,
    DESCRIPCION_EQUIPO VARCHAR2(500)
);


CREATE TABLE PERSONAL_IR (
    PERSONAL_IR_ID CHAR(10) PRIMARY KEY,
    NOMBRE_PERSONAL_IR VARCHAR2(100) NOT NULL,
    APELLIDO_PERSONAL_IR VARCHAR2(100) NOT NULL,
    ROL_PERSONAL_IR VARCHAR2(50) NOT NULL,
    EQUIPO_ID CHAR(10) NOT NULL,
    CONSTRAINT FK_PERSONAL_IR_EQUIPO FOREIGN KEY (EQUIPO_ID) REFERENCES EQUIPO_IR(EQUIPO_ID) ON DELETE CASCADE
);


CREATE TABLE VULNERABILIDAD (
    VULNERABILIDAD_ID CHAR(10) PRIMARY KEY,
    NOMBRE_VULNERABILIDAD VARCHAR2(100) NOT NULL,
    DESCRIPCION_VULNERABILIDAD VARCHAR2(500) NOT NULL
);


CREATE TABLE RESPUESTA_INCIDENTE (
    RESPUESTA_ID CHAR(10) PRIMARY KEY,
    EQUIPO_ID CHAR(10) NOT NULL,
    INCIDENTE_ID CHAR(10) NOT NULL,
    VULNERABILIDAD_ID CHAR(10) NOT NULL,
    MEDIDAS_CONTENCION VARCHAR2(500) NOT NULL,
    NIVEL_ERRADICACION VARCHAR2(20) NOT NULL CHECK (NIVEL_ERRADICACION IN ('Baja', 'Media', 'Alta', 'Total')),
    CONSTRAINT FK_RESPUESTA_INCIDENTE_EQUIPO FOREIGN KEY (EQUIPO_ID) REFERENCES EQUIPO_IR(EQUIPO_ID) ON DELETE CASCADE,
    CONSTRAINT FK_RESPUESTA_INCIDENTE_INCIDENTE FOREIGN KEY (INCIDENTE_ID) REFERENCES INCIDENTE(INCIDENTE_ID) ON DELETE CASCADE,
    CONSTRAINT FK_RESPUESTA_INCIDENTE_VULNERABILIDAD FOREIGN KEY (VULNERABILIDAD_ID) REFERENCES VULNERABILIDAD(VULNERABILIDAD_ID) ON DELETE CASCADE
);


CREATE TABLE VULNERABILIDAD_ACTIVO (
    VULNERABILIDAD_ID CHAR(10),
    ACTIVO_ID CHAR(10),
    DATOS_COMPROMETIDOS VARCHAR2(500),
    PRIMARY KEY (VULNERABILIDAD_ID, ACTIVO_ID),
    CONSTRAINT FK_VULNERABILIDAD_ACTIVO_VULNERABILIDAD FOREIGN KEY (VULNERABILIDAD_ID) REFERENCES VULNERABILIDAD(VULNERABILIDAD_ID) ON DELETE CASCADE,
    CONSTRAINT FK_VULNERABILIDAD_ACTIVO_ACTIVO FOREIGN KEY (ACTIVO_ID) REFERENCES ACTIVO(ACTIVO_ID) ON DELETE CASCADE
);
