-- Borrados en RESPUESTA_INCIDENTE
DELETE FROM RESPUESTA_INCIDENTE WHERE RESPUESTA_ID = 'R001';


-- Borrados en INCIDENTE (Primero eliminamos RESPUESTA_INCIDENTE asociados)
DELETE FROM RESPUESTA_INCIDENTE WHERE INCIDENTE_ID = 'I001';
DELETE FROM INCIDENTE WHERE INCIDENTE_ID = 'I001';


-- Borrados en ACTIVO (Primero eliminamos VULNERABILIDAD_ACTIVO asociados)
DELETE FROM VULNERABILIDAD_ACTIVO WHERE ACTIVO_ID = 'A001';
DELETE FROM ACTIVO WHERE ACTIVO_ID = 'A001';

